### PR TITLE
Bugfix/shit fuck healthbars - AKA a bunch of fixes related to health bars and some other refactorings

### LINKED ISSUE #7: Player dies and respawns + fix healthbars

### PR DESCRIPTION
**Pull request by lcgonsalves**
READ THE TITLE. THIS IS A MESSY ONE. LET ME TRY TO RECALL (you're better off reading the diff)

- health bars would not empty out completely when health component dies FIXED
- player health bar spawns with incorrect information FIXED
- enemy health bars would render also directly opposed to where they should be FIXED
- enemies follow you when you shoot them (got bored of them just always taking it on the chin without fighting back)
- refactor: made a generic object pool class (finally godamn)
- refactor: used generic object pool to rebuild BulletSystem as a static class
- refactor: navigation component is more generic, allowing any transform to be used as a waypoint. If said transform is a waypoint, the navigation is still capable of traversing the chain, but now all methods are usable with Transforms.

+ some other stuff, probably

### CODE REVIEW

File: Scripts/BehaviorDesignerTasks/ScanForTargets.cs [hunk 1]
```diff
@@ -41,26 +41,31 @@ public override TaskStatus OnUpdate()
...
             FindClosestTarget(gm, self.Value.transform.position, maximumRange.Value, gm.side.GetOpposing(), out var closestTarget);
 
+            nearestLivingTarget?.SetValue(closestTarget?.transform);
+
             var ragdoll = closestTarget != null ? closestTarget.GetComponent<Ragdoll>() : null;
             
             Transform target = null;
 
-            if (ragdoll) target = ragdoll.neck;
+            if (ragdoll) target = (Transform) ragdoll.neck;
```
Comment (lcgonsalves) [inline Scripts/BehaviorDesignerTasks/ScanForTargets.cs:50]: Cache class I wrote can be explicitly cast as well as using the Get method.

File: Scripts/Bullet/ImpactParticleSpawner.cs [hunk 2]
```diff
@@ -40,7 +40,7 @@ private void OnCollisionEnter(Collision other)
                 if (healthComponent && limbComponent)
                 {
                     // todo: actually take into account the multiplier
-                    healthComponent.Damage(controller.Settings.GetDamageAmount());
+                    healthComponent.Damage(controller.Settings.GetDamageAmount(), controller);
```
Comment (lcgonsalves) [inline Scripts/Bullet/ImpactParticleSpawner.cs:43]: damage can now be traced to source
